app/posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app/posts/blueprint.py
from flask import Blueprint, render_template
from flask import request
from models import Post, Tag
from app import db
from .forms import PostForm
from flask import redirect
from flask import url_for

from flask_security import login_required

posts = Blueprint('posts', __name__, template_folder='templates')


# http://localhost/blog/create
@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        if title != "":
            try:
                post = Post(title=title, body=body)
                db.session.add(post)
                db.session.commit()
            except Exception as e:
                print('Something wrong! ', e)
            return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


@posts.route('/')
def index():
    q = request.args.get('q')
    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        l_posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))  # .all()
    else:
        l_posts = Post.query.order_by(Post.id)  # (Post.created.desc()) # .all()

    pages = l_posts.paginate(page=page, per_page=5)
    return render_template('posts/index.html', posts=l_posts, pages=pages)


# http://localhost/blog/firs-post
@posts.route('/<slug>')
def post_detail(slug):
    l_post = Post.query.filter(Post.slug == slug).first_or_404()
    l_tags = l_post.tags
    return render_template('posts/post_detail.html', post=l_post, tags=l_tags)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    l_tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    l_posts = l_tag.posts.all()
    return render_template('posts/tag_detail.html', tag=l_tag, posts=l_posts)

app/posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
 Create new post
{% endblock %}

{% block content_title %}
    New post
{% endblock %}

{%block content%}
<div class="col-md-6">
    <form action="{{ url_for('posts.create_post') }}" method="POST">
        {% for field in form %}
            <div class=".form-group">
                {{ field.label(class='control-label') }}
                {{ field(class='form-control') }}
            </div>
        {% endfor %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <button class="btn btn-success" type="submit">Create</button>
        </div>
    </form>
    </div>
{% endblock%}

app/posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
 Edit post
{% endblock %}

{% block content_title %}
    Edit post
{% endblock %}

{%block content%}
<div class="col-md-6">
    <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">
        {% for field in form %}
            <div class=".form-group">
                {{ field.label(class='control-label') }}
                {{ field(class='form-control') }}
            </div>
        {% endfor %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <button class="btn btn-success" type="submit">Update</button>
        </div>
    </form>
    </div>
{% endblock%}

app/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  Blueprint index page
{% endblock %}

{% block content_title %}
  Posts <a href="{{url_for('posts.create_post')}}" type="button" class="btn btn-outline-primary" >+</a>

{% endblock %}

{%block content%}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title</th>
          <th scope="col">date</th>
          <th scope="col">Edit/Del</th>
        </tr>
      </thead>
  <tbody>
    {% for post in pages.items %}
    <tr>
      <th scope="row"><a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{post.id}}</a></th>
      <td><a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{post.title}}</a></td>
      <td>{{post.created}}</td>
      <td>
        <a href="{{url_for('posts.edit_post',slug=post.slug)}}" type="button">
        <svg type="button" class="bi bi-pen" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
          <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
        </svg>
        </a>
        <svg type="button" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash-circle" viewBox="0 0 16 16">
          <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
          <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"/>
        </svg>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

  <nav aria-label="...">
    <ul class="pagination">
      <li {% if pages.has_prev %} class="page-item" {% else %} class="page-item disabled" {% endif %}>
        <a class="page-link" href="./?page={{ pages.prev_num}}" tabindex="-1" aria-disabled="true">&laquo;</a>
      </li>

      {% for page in pages.iter_pages() %}
        <li {% if page == pages.page %} class="page-item active" aria-current="page" {% else %} class="page-item" {% endif %}>
          <a class="page-link" href="./?page={{page}}">{{ page }}</a>
        </li>
      {% endfor%}

      <li {% if pages.next_num %} class="page-item" {% else %} class="page-item disabled" {% endif %}>
        <a class="page-link" href="./?page={{ pages.next_num}}">&raquo;</a>
      </li>
    </ul>
  </nav>
{% endblock%}

app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
  {{post.title}}
{% endblock %}

{% block content_title %}
    {{post.title}}
{% endblock %}

{%block content%}
    <div class="tags">
        {% for tag in tags %}
        <a href="{{url_for('posts.tag_detail', slug=tag.slug)}}">
            <span class="badge bg-primary">{{ tag.name }}</span>
        </a>
        {% endfor %}
    </div>

    <div class="main-content">
        {{post.body}}
    </div>
{% endblock%}

app/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ tag.name }}
{% endblock %}

{% block content_title %}
    Posts for  <span class="badge bg-primary">{{ tag.name }}</span>
{% endblock %}

{%block content%}
    {% for post in posts %}
        <div class="post">
            <a href="{{ url_for('posts.post_detail', slug=post.slug)}}">{{post.title}}</a>
        </div>
    {% endfor %}
{% endblock%}